# Clustering Alcohol Features

This analysis clusters haunted locations based on alcohol-related deaths, reported supernatural entities, and the time of reported hauntings. The features used for clustering are:

* Total_Deaths: The total number of alcohol-related deaths in the area.
* Percent_Under_21: The percentage of alcohol-related deaths involving individuals under the age of 21.
* Apparition_Type: The type of supernatural entity reported (e.g., ghost, demon, spirit, orb).
* Time_of_Day: The time when the supernatural event was reported (e.g., dusk, evening, morning, unknown).
* State

By analyzing these factors, this clustering aims to investigate whether areas with higher alcohol-related deaths report more supernatural activity and whether certain apparition types and haunting times are more commonly associated with areas where alcohol-related mortality is higher, particularly among younger individuals.

# Generating Indices

The indices were chosen to ensure a balanced and representative sample of haunted places based on alcohol-related deaths, apparition type, and daylight duration. First, 500 haunted places in states with the highest alcohol-related deaths and 500 in states with the lowest alcohol-related deaths were selected. This selection was based on "Total_Deaths" and "Percent_Under_21" to compare supernatural activity in areas with varying levels of alcohol-related mortality.

Next, a diverse sample of up to 100 hauntings per apparition type was included to analyze how different supernatural experiences may correlate with alcohol-related deaths. This step ensures that a broad range of apparitions—such as ghosts, demons, spirits, and orbs—are fairly represented in the dataset. Additionally, 500 haunted places were selected based on daylight duration, with 250 locations experiencing the lowest daylight duration (<9.5 hours) and 250 with the highest daylight duration (>10.5 hours) to investigate whether lighting conditions influence paranormal reports.

In [69]:
# Number of rows to select per extreme group
num_rows_per_group = 500  

# Select haunted places in states with the HIGHEST alcohol-related deaths
high_alcohol_deaths = df.sort_values(by=['Total_Deaths', 'Percent_Under_21'], ascending=[False, False]).head(num_rows_per_group)

# Select haunted places in states with the LOWEST alcohol-related deaths
low_alcohol_deaths = df.sort_values(by=['Total_Deaths', 'Percent_Under_21'], ascending=[True, True]).head(num_rows_per_group)

# Get the index numbers of these rows
high_indices = high_alcohol_deaths.index.tolist()
low_indices = low_alcohol_deaths.index.tolist()

# Combine both sets of indices
selected_indices = high_indices + low_indices

# Select a subset of hauntings by apparition type
selected_hauntings = df.loc[selected_indices].groupby('Apparition_Type').apply(lambda x: x.sample(n=min(100, len(x)), random_state=42))

# Get the indices of selected hauntings by apparition type
apparition_indices = selected_hauntings.index.get_level_values(1).tolist()

# Select haunted places with the LOWEST daylight duration
low_light = df[df['Daylight_Duration_Hours'] < 9.5].sample(250, random_state=42)

# Select haunted places with the HIGHEST daylight duration
high_light = df[df['Daylight_Duration_Hours'] > 10.5].sample(250, random_state=42)

# Get the index numbers of these rows
low_light_indices = low_light.index.tolist()
high_light_indices = high_light.index.tolist()

# Combine all selected indices
final_selected_indices = apparition_indices + low_light_indices + high_light_indices

# # Print the final indices
# print(final_selected_indices)

# Jaccard

In [148]:
import pandas as pd

# Display all rows and columns
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_colwidth', None)  # Show full text in each cell
pd.set_option('display.expand_frame_repr', False)  # Prevent wrapping

In [135]:
import pandas as pd
import os
import sys 

parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(parent_dir)

from dsci_550_a1.unpack_circles import unpack_cluster

haunted_places = "../data/processed/haunted_places_features_added.tab"

df = pd.read_csv(haunted_places, sep = "\t")

clusters = unpack_cluster("../clustering/jaccard/alcohol/visualization/clusters.json")

cluster_labels = {}  # Create a dictionary to map row indices to cluster labels

for cluster_name, indices in clusters.items():
    for index in indices:
        cluster_labels[index] = cluster_name  # Assign cluster name

# Add the 'Cluster' column
df["Cluster"] = df.index.map(cluster_labels)

### Investigating Jaccard Clusters

In [150]:
df.groupby(['State', 'Cluster'])[['Total_Deaths', 'Percent_Under_21']].describe()

                         Total_Deaths                     Percent_Under_21
                                count unique     top freq            count unique    top freq
State          Cluster
Alabama        cluster 1            5      1   2,208    5                5      1  3.90%    5
Alaska         cluster 1            7      1     433    7                7      1  3.90%    7
               cluster 2            4      1     433    4                4      1  3.90%    4
Arizona        cluster 1            1      1   3,670    1                1      1  2.80%    1
Arkansas       cluster 1            1      1   1,407    1                1      1  3.60%    1
California     cluster 1           12      1  15,443   12               12      1  2.50%   12
               cluster 2            1      1  15,443    1                1      1  2.50%    1
Colorado       cluster 1            1      1   2,623    1                1      1  2.80%    1
               cluster 2            5      1   2,623    5                5      1  2.80%    5
Connecticut    cluster 1           15      2   1,426   13               15      2  2.20%   13
Delaware       cluster 1           11      2     466    8               11      2  2.80%    8
               cluster 2            1      1     466    1                1      1  2.80%    1
Florida        cluster 1           12      2  10,655   10               12      2  2.30%   10
               cluster 2           10      2  10,655    9               10      2  2.30%    9
Georgia        cluster 1            8      1   3,953    8                8      1  3.70%    8
Hawaii         cluster 0            2      1     526    2                2      1  2.30%    2
               cluster 1           37      2     526   29               37      2  2.30%   29
               cluster 2           17      2     526   13               17      2  2.30%   13
Idaho          cluster 1           13      2     732   10               13      2  3.00%   10
               cluster 2           11      2     732    7               11      2  3.00%    7
Illinois       cluster 1           15      2   2,960   12               15      2  3.40%   12
               cluster 2            9      2   2,960    7                9      2  3.40%    7
Indiana        cluster 1           16      2   5,151    9               16      2  3.50%    9
Iowa           cluster 1            7      2   1,305    6                7      2  2.50%    6
               cluster 2            3      1   1,305    3                3      1  2.50%    3
Kansas         cluster 1            3      1   1,146    3                3      1  3.10%    3
Kentucky       cluster 1            3      1   2,206    3                3      1  2.70%    3
               cluster 2            6      2   2,206    5                6      2  2.70%    5
Louisiana      cluster 1            2      1   2,278    2                2      1  4.10%    2
Maine          cluster 1           16      1     714   16               16      1  1.70%   16
               cluster 2            4      1     714    4                4      1  1.70%    4
Maryland       cluster 1            2      1   2,482    2                2      1  3.20%    2
               cluster 2            2      1   2,482    2                2      1  3.20%    2
Massachusetts  cluster 0            1      1   2,760    1                1      1  1.90%    1
               cluster 1           17      1   2,760   17               17      1  1.90%   17
Michigan       cluster 1           18      1   4,548   18               18      1  2.60%   18
               cluster 2           19      1   4,548   19               19      1  2.60%   19
Minnesota      cluster 1            6      2   2,082    5                6      2  2.30%    5
Mississippi    cluster 1            1      1   1,426    1                1      1  2.20%    1
Missouri       cluster 1            8      2   2,877    4                8      2  3.70%    4
               cluster 2            4      2   2,877    3                4      2  3.70%    3
Montana        cluster 1            1      1     605    1                1      1  2.80%    1
               cluster 2            3      2     605    2                3      2  2.80%    2
Nebraska       cluster 1           34      2     720   33               34      2  3.10%   33
               cluster 2            5      1     720    5                5      1  3.10%    5
Nevada         cluster 1            8      1     526    8                8      1  2.30%    8
               cluster 2            2      1     526    2                2      1  2.30%    2
New Hampshire  cluster 1           21      3     661   13               21      3  1.70%   13
               cluster 2            5      2     661    4                5      2  1.70%    4
New Jersey     cluster 1            5      1   3,008    5                5      1  2.20%    5
               cluster 2            4      1   3,008    4                4      1  2.20%    4
New Mexico     cluster 2            3      2   1,581    2                3      2  2.60%    2
New York       cluster 1           17      2   6,701   12               17      2  2.00%   12
               cluster 2           12      2   6,701    7               12      2  2.00%    7
North Carolina cluster 1            1      1   2,206    1                1      1  2.70%    1
North Dakota   cluster 1            8      1     347    8                8      1  2.60%    8
               cluster 2            5      1     347    5                5      1  2.60%    5
Ohio           cluster 1           17      1   5,739   17               17      1  2.60%   17
               cluster 2            2      1   5,739    2                2      1  2.60%    2
Oklahoma       cluster 1            2      1   2,104    2                2      1  2.80%    2
               cluster 2            2      1   2,104    2                2      1  2.80%    2
Oregon         cluster 1           10      1   2,186   10               10      1  2.00%   10
               cluster 2            2      1   2,186    2                2      1  2.00%    2
Pennsylvania   cluster 1           48      1   5,703   48               48      1  2.70%   48
               cluster 2           12      1   5,703   12               12      1  2.70%   12
Rhode Island   cluster 0            1      1     493    1                1      1  1.40%    1
               cluster 1           22      2     493   20               22      2  1.40%   20
               cluster 2            5      1     493    5                5      1  1.40%    5
South Carolina cluster 1            6      2     493    4                6      2  1.40%    4
               cluster 2            2      1     493    2                2      1  1.40%    2
South Dakota   cluster 1           14      1     463   14               14      1  3.90%   14
               cluster 2            7      2     463    6                7      1  3.90%    7
Tennessee      cluster 1            3      1   3,359    3                3      1  2.90%    3
Texas          cluster 1           31      3  10,647   23               31      3  4.00%   23
               cluster 2            5      2  10,647    4                5      2  4.00%    4
Utah           cluster 0            1      1     903    1                1      1  3.80%    1
               cluster 1           49      2     903   43               49      2  3.80%   43
               cluster 2            5      2     903    4                5      2  3.80%    4
Vermont        cluster 1           17      2     332   16               17      2  1.50%   16
               cluster 2            4      1     332    4                4      1  1.50%    4
Virginia       cluster 1            9      2     732    5                9      2  3.00%    5
               cluster 2            3      2     732    2                3      2  3.00%    2
Washington     cluster 1            6      2   3,184    4                6      2  1.80%    4
               cluster 2            4      1   3,184    4                4      1  1.80%    4
Washington DC  cluster 1            4      1     347    4                4      1  2.60%    4
               cluster 2            2      1     347    2                2      1  2.60%    2
West Virginia  cluster 1            1      1   1,037    1                1      1  2.00%    1
Wisconsin      cluster 1           17      3   2,651    8               17      3  2.30%    8
               cluster 2            1      1   2,651    1                1      1  2.30%    1
Wyoming        cluster 1           16      3     347   14               16      3  2.60%   14
               cluster 2            9      1     347    9                9      1  2.60%    9

In [152]:
df.groupby(['State', 'Cluster', 'Apparition_Type'])['Time_of_Day'].value_counts(normalize=True).unstack()

Time_of_Day                                           Dusk   Evening   Morning   Unknown
State          Cluster   Apparition_Type
Alabama        cluster 1 Evil Presence                 NaN  1.000000       NaN       NaN
                         Phantom                       NaN       NaN       NaN  1.000000
                         Unknown                       NaN  0.333333       NaN  0.666667
Alaska         cluster 1 Unknown                       NaN       NaN       NaN  1.000000
                         Female Ghost, Ghost           NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
Arizona        cluster 1 Unknown                       NaN       NaN       NaN  1.000000
Arkansas       cluster 1 Unknown                       NaN  1.000000       NaN       NaN
California     cluster 1 Unknown                       NaN  0.444444       NaN  0.555556
                         Ghost                         NaN  1.000000       NaN       NaN
                         Spirit                        NaN  0.500000       NaN  0.500000
               cluster 2 Spirit                        NaN       NaN       NaN  1.000000
Colorado       cluster 1 Unknown                       NaN  1.000000       NaN       NaN
                         Spirit                        NaN  1.000000       NaN       NaN
               cluster 2 Unknown                       NaN  0.400000  0.200000  0.400000
Connecticut    cluster 1 Unknown                       NaN  0.428571       NaN  0.571429
                         Ghost                         NaN  0.200000  0.200000  0.600000
                         Ghost, Orb                    NaN       NaN       NaN  1.000000
                         Ghost, Spirit                 NaN  1.000000       NaN       NaN
Delaware       cluster 1 Unknown                       NaN  1.000000       NaN       NaN
                         Ghost                         NaN  0.333333       NaN  0.666667
                         Spirit                        NaN       NaN       NaN  1.000000
                         Ghost, Orb                    NaN       NaN       NaN  1.000000
                         Evil Presence, Ghost          NaN  1.000000       NaN       NaN
                         Orb                           NaN  1.000000       NaN       NaN
               cluster 2 Ghost                         NaN       NaN       NaN  1.000000
Florida        cluster 1 Unknown                       NaN  0.200000       NaN  0.800000
                         Ghost                         NaN  0.250000  0.250000  0.500000
                         Spirit                        NaN       NaN       NaN  1.000000
                         Orb                           NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.250000       NaN  0.750000
                         Orb                           NaN  0.500000       NaN  0.500000
Georgia        cluster 1 Unknown                       NaN  0.285714  0.142857  0.571429
                         Ghost                         NaN  1.000000       NaN       NaN
Hawaii         cluster 0 Unknown                       NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 1 Unknown                       NaN  0.400000       NaN  0.600000
                         Female Ghost, Ghost           NaN       NaN       NaN  1.000000
                         Ghost                         NaN  0.142857       NaN  0.857143
                         Spirit                        NaN  1.000000       NaN       NaN
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.333333  0.083333  0.583333
                         Spirit                        NaN       NaN  0.250000  0.750000
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
Idaho          cluster 1 Unknown                       NaN       NaN  1.000000       NaN
                         Ghost                         NaN  0.600000       NaN  0.400000
                         Spirit                        NaN  0.166667       NaN  0.833333
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.200000       NaN  0.800000
                         Ghost, Phantom                NaN       NaN       NaN  1.000000
Illinois       cluster 1 Unknown                       NaN  0.285714       NaN  0.714286
                         Ghost                         NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN  0.500000  0.500000
                         Demon, Spirit                 NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.125000       NaN  0.875000
                         Ghost                         1.0       NaN       NaN       NaN
Indiana        cluster 1 Unknown                       NaN  0.307692       NaN  0.692308
                         Ghost                         NaN  0.500000       NaN  0.500000
                         Spirit                        NaN  1.000000       NaN       NaN
Iowa           cluster 1 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN  0.500000       NaN  0.500000
                         Orb                           NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
Kansas         cluster 1 Unknown                       NaN  0.666667       NaN  0.333333
Kentucky       cluster 1 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.166667       NaN  0.833333
Louisiana      cluster 1 Unknown                       NaN  0.500000       NaN  0.500000
Maine          cluster 1 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN  0.166667  0.833333
                         Spirit                        NaN  0.250000  0.250000  0.500000
                         Ghost, Orb                    NaN       NaN       NaN  1.000000
                         Ghost, Spirit                 NaN  0.500000       NaN  0.500000
                         Orb                           NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.250000       NaN  0.750000
Maryland       cluster 1 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.500000       NaN  0.500000
Massachusetts  cluster 0 Ghost                         NaN       NaN       NaN  1.000000
               cluster 1 Unknown                       NaN  0.250000  0.083333  0.666667
                         Ghost                         NaN       NaN  0.250000  0.750000
                         Spirit                        NaN       NaN       NaN  1.000000
Michigan       cluster 1 Phantom                       NaN  1.000000       NaN       NaN
                         Unknown                       NaN  0.444444       NaN  0.555556
                         Ghost                         NaN  0.400000  0.200000  0.400000
                         Spirit                        NaN  0.500000       NaN  0.500000
                         Demon, Ghost, Orb             NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.222222  0.055556  0.722222
                         Orb                           NaN       NaN       NaN  1.000000
Minnesota      cluster 1 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN  0.500000       NaN  0.500000
Mississippi    cluster 1 Unknown                       NaN       NaN       NaN  1.000000
Missouri       cluster 1 Unknown                       NaN  0.400000       NaN  0.600000
                         Ghost                         NaN       NaN       NaN  1.000000
                         Spirit                        NaN  1.000000       NaN       NaN
                         Orb                           NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.666667       NaN  0.333333
                         Ghost                         NaN       NaN       NaN  1.000000
Montana        cluster 1 Ghost, Spirit                 NaN  1.000000       NaN       NaN
               cluster 2 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN       NaN  1.000000
                         Spirit                        NaN  1.000000       NaN       NaN
Nebraska       cluster 1 Phantom                       NaN  0.500000       NaN  0.500000
                         Unknown                       NaN  0.375000  0.062500  0.562500
                         Ghost                         NaN  0.125000       NaN  0.875000
                         Spirit                        NaN       NaN  0.500000  0.500000
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
                         Female Ghost, Ghost, Spirit   NaN       NaN       NaN  1.000000
                         Floating Light, Ghost         NaN  1.000000       NaN       NaN
               cluster 2 Ghost                         NaN  0.800000  0.200000       NaN
Nevada         cluster 1 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
New Hampshire  cluster 1 Unknown                       NaN  0.400000       NaN  0.600000
                         Ghost                         NaN  0.333333       NaN  0.666667
                         Spirit                        NaN  0.500000       NaN  0.500000
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
                         Ghost, Phantom                NaN       NaN       NaN  1.000000
                         Demon, Ghost, Orb             NaN       NaN       NaN  1.000000
               cluster 2 Spirit                        NaN  0.200000       NaN  0.800000
New Jersey     cluster 1 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.500000       NaN  0.500000
New Mexico     cluster 2 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN  1.000000       NaN       NaN
New York       cluster 1 Unknown                       NaN  0.571429       NaN  0.428571
                         Ghost                         NaN  0.200000       NaN  0.800000
                         Spirit                        NaN  0.333333       NaN  0.666667
                         Ghost, Spirit                 NaN  1.000000       NaN       NaN
                         Orb                           NaN  1.000000       NaN       NaN
               cluster 2 Unknown                       NaN  0.250000  0.083333  0.666667
North Carolina cluster 1 Unknown                       NaN       NaN       NaN  1.000000
North Dakota   cluster 1 Unknown                       NaN  0.666667       NaN  0.333333
                         Ghost                         NaN  0.333333  0.333333  0.333333
                         Spirit                        NaN  0.500000       NaN  0.500000
               cluster 2 Unknown                       NaN  0.333333  0.333333  0.333333
                         Ghost                         NaN  1.000000       NaN       NaN
Ohio           cluster 1 Phantom                       NaN  1.000000       NaN       NaN
                         Unknown                       NaN  0.461538       NaN  0.538462
                         Ghost                         NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  1.000000       NaN       NaN
                         Spirit                        NaN       NaN       NaN  1.000000
Oklahoma       cluster 1 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN  1.000000       NaN       NaN
               cluster 2 Unknown                       NaN       NaN       NaN  1.000000
Oregon         cluster 1 Unknown                       NaN  0.333333       NaN  0.666667
                         Ghost, Spirit                 NaN  1.000000       NaN       NaN
               cluster 2 Ghost                         NaN  0.500000       NaN  0.500000
Pennsylvania   cluster 1 Phantom                       NaN       NaN  0.333333  0.666667
                         Unknown                       NaN  0.250000       NaN  0.750000
                         Ghost                         NaN  0.166667       NaN  0.833333
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 2 Ghost                         NaN  0.090909  0.090909  0.818182
                         Orb                           NaN       NaN       NaN  1.000000
Rhode Island   cluster 0 Spirit                        NaN       NaN       NaN  1.000000
               cluster 1 Unknown                       NaN       NaN  0.333333  0.666667
                         Ghost                         NaN  0.250000       NaN  0.750000
                         Spirit                        NaN       NaN  0.166667  0.833333
                         Ghost, Spirit                 NaN  0.400000       NaN  0.600000
                         Orb                           NaN       NaN       NaN  1.000000
                         Ghost, Phantom                NaN       NaN       NaN  1.000000
                         Demon                         NaN  1.000000       NaN       NaN
                         Ghost, Male Ghost             NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.250000       NaN  0.750000
                         Ghost                         NaN  1.000000       NaN       NaN
South Carolina cluster 1 Phantom                       NaN       NaN       NaN  1.000000
                         Unknown                       NaN  0.500000       NaN  0.500000
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 2 Ghost                         NaN  1.000000       NaN       NaN
                         Orb                           NaN       NaN       NaN  1.000000
South Dakota   cluster 1 Phantom                       NaN  1.000000       NaN       NaN
                         Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN  1.000000       NaN       NaN
                         Spirit                        NaN       NaN       NaN  1.000000
                         Ghost, Orb                    NaN       NaN       NaN  1.000000
                         Ghost, Spirit                 NaN  0.333333       NaN  0.666667
                         Orb                           NaN       NaN       NaN  1.000000
                         Floating Light                NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN  0.666667       NaN  0.333333
Tennessee      cluster 1 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN       NaN  1.000000
Texas          cluster 1 Unknown                       NaN  0.473684       NaN  0.526316
                         Ghost                         NaN  0.555556  0.111111  0.333333
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 2 Ghost                         NaN  0.666667       NaN  0.333333
                         Ghost, Phantom                NaN       NaN       NaN  1.000000
                         Demon                         NaN       NaN       NaN  1.000000
Utah           cluster 0 Unknown                       NaN       NaN       NaN  1.000000
               cluster 1 Unknown                       NaN  0.086957  0.086957  0.826087
                         Ghost                         NaN  0.235294  0.058824  0.705882
                         Spirit                        NaN  0.333333       NaN  0.666667
                         Ghost, Orb                    NaN       NaN       NaN  1.000000
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
                         Orb                           NaN  0.333333       NaN  0.666667
               cluster 2 Evil Presence                 NaN  0.333333       NaN  0.666667
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
Vermont        cluster 1 Evil Presence                 NaN  1.000000       NaN       NaN
                         Unknown                       NaN  0.250000       NaN  0.750000
                         Female Ghost, Ghost           NaN  0.500000       NaN  0.500000
                         Spirit                        NaN  1.000000       NaN       NaN
                         Ghost, Orb                    NaN       NaN       NaN  1.000000
                         Orb                           NaN       NaN       NaN  1.000000
                         Ghost, Phantom                NaN       NaN       NaN  1.000000
               cluster 2 Ghost                         NaN  0.500000       NaN  0.500000
Virginia       cluster 1 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN  0.250000       NaN  0.750000
                         Spirit                        NaN  1.000000       NaN       NaN
               cluster 2 Unknown                       NaN       NaN  1.000000       NaN
                         Ghost                         NaN       NaN       NaN  1.000000
Washington     cluster 1 Unknown                       NaN       NaN       NaN  1.000000
                         Orb                           NaN  0.500000       NaN  0.500000
               cluster 2 Unknown                       NaN  0.250000       NaN  0.750000
Washington DC  cluster 1 Ghost                         NaN  0.250000       NaN  0.750000
               cluster 2 Spirit                        NaN  0.500000       NaN  0.500000
West Virginia  cluster 1 Unknown                       NaN       NaN       NaN  1.000000
Wisconsin      cluster 1 Unknown                       NaN  0.307692       NaN  0.692308

In [154]:
df.groupby(['State', 'Cluster']).size().unstack(fill_value=0)

Cluster         cluster 0  cluster 1  cluster 2
State
Alabama                 0          5          0
Alaska                  0          7          4
Arizona                 0          1          0
Arkansas                0          1          0
California              0         12          1
Colorado                0          2          5
Connecticut             0         15          0
Delaware                0         11          1
Florida                 0         12         10
Georgia                 0          8          0
Hawaii                  2         37         17
Idaho                   0         13         11
Illinois                0         15          9
Indiana                 0         16          0
Iowa                    0          7          3
Kansas                  0          3          0
Kentucky                0          3          6
Louisiana               0          2          0
Maine                   0         16          4
Maryland                0          2          2
Massachusetts           1         17          0
Michigan                0         18         19
Minnesota               0          6          0
Mississippi             0          1          0
Missouri                0          8          4
Montana                 0          1          3
Nebraska                0         34          5
Nevada                  0          8          2
New Hampshire           0         21          5
New Jersey              0          5          4
New Mexico              0          0          3
New York                0         17         12
North Carolina          0          1          0
North Dakota            0          8          5
Ohio                    0         17          2
Oklahoma                0          2          2
Oregon                  0         10          2
Pennsylvania            0         48         12
Rhode Island            1         22          5
South Carolina          0          6          2
South Dakota            0         14          7
Tennessee               0          3          0
Texas                   0         31          5
Utah                    1         49          5
Vermont                 0         17          4
Virginia                0          9          3
Washington              0          6          4
Washington DC           0          4          2
West Virginia           0          1          0
Wisconsin               0         17          1
Wyoming                 0         16          9

In [156]:
df.pivot_table(index=['State', 'Cluster'], columns='Apparition_Type', values='Daylight_Duration_Hours', aggfunc='mean')

Apparition_Type            Demon  Demon, Ghost, Orb  Demon, Spirit  Evil Presence  Evil Presence, Ghost  Female Ghost, Ghost  Female Ghost, Ghost, Spirit  Floating Light  Floating Light, Ghost      Ghost  Ghost, Male Ghost  Ghost, Orb  Ghost, Phantom  Ghost, Spirit        Orb  Phantom     Spirit    Unknown
State          Cluster
Alabama        cluster 1     NaN                NaN            NaN      13.527000                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN  13.5090        NaN  11.520667
Alaska         cluster 1     NaN                NaN            NaN            NaN                   NaN               5.7880                          NaN             NaN                    NaN   4.986000                NaN         NaN             NaN            NaN        NaN      NaN   5.747500   5.108000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN   5.898000   5.895000
Arizona        cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  13.454000
Arkansas       cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  14.317000
California     cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.612000                NaN         NaN             NaN            NaN        NaN      NaN  11.630000  11.590333
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN  11.074000        NaN
Colorado       cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN  11.504000   9.457000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  12.908600
Connecticut    cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.248600                NaN       9.259             NaN      12.198000        NaN      NaN        NaN  10.652714
Delaware       cluster 1     NaN                NaN            NaN            NaN                 9.478                  NaN                          NaN             NaN                    NaN   9.442000                NaN       9.490             NaN            NaN   9.511000      NaN   9.439500  11.402000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.484000                NaN         NaN             NaN            NaN        NaN      NaN        NaN        NaN
Florida        cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.942250                NaN         NaN             NaN            NaN  11.923000      NaN  10.574000  11.162200
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN  10.567000      NaN        NaN  11.031375
Georgia        cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.492000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  12.491286
Hawaii         cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN  10.938000  10.901000
               cluster 1     NaN                NaN            NaN            NaN                   NaN              10.9000                          NaN             NaN                    NaN  10.913929                NaN         NaN             NaN      10.899000        NaN      NaN  10.906000  11.112150
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN      10.884000        NaN      NaN  11.447500  11.094833
Idaho          cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.933400                NaN         NaN             NaN       9.145000        NaN      NaN   9.046167  13.339000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN          10.362            NaN        NaN      NaN        NaN   9.730000
Illinois       cluster 1     NaN                NaN          9.211            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.803000                NaN         NaN             NaN            NaN        NaN      NaN   9.313500  10.617286
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.433000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  10.623375
Indiana        cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.406000                NaN         NaN             NaN            NaN        NaN      NaN  14.403000  10.948000
Iowa           cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  12.286000                NaN         NaN             NaN            NaN  15.159000      NaN        NaN  10.477250
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN  14.382000   9.211500
Kansas         cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  11.575000
Kentucky       cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.757000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  14.255500
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  13.833167
Louisiana      cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  12.025000
Maine          cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.013000                NaN       8.965             NaN       8.998500   9.046500      NaN   8.823500   9.056000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN   9.091250
Maryland       cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.478000                NaN         NaN             NaN            NaN        NaN      NaN        NaN   9.473000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN   9.476000
Massachusetts  cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  14.276000                NaN         NaN             NaN            NaN        NaN      NaN        NaN        NaN
               cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.187750                NaN         NaN             NaN            NaN        NaN      NaN   9.160000  10.196667
Michigan       cluster 1     NaN             11.242            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.894800                NaN         NaN             NaN            NaN        NaN   9.1530  10.477000   9.815667
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN   9.216000      NaN        NaN  10.282000
Minnesota      cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.975000                NaN         NaN             NaN            NaN        NaN      NaN        NaN   9.454500
Mississippi    cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  13.493000
Missouri       cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.748000                NaN         NaN             NaN            NaN   9.565000      NaN   9.654000  10.623600
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.564000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  13.309000
Montana        cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN       8.781000        NaN      NaN        NaN        NaN
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.269000                NaN         NaN             NaN            NaN        NaN      NaN   8.731000   8.733000
Nebraska       cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                        9.422             NaN                  9.385   9.686000                NaN         NaN             NaN       9.299000        NaN   9.3665   9.345750   9.610625
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.350200                NaN         NaN             NaN            NaN        NaN      NaN        NaN        NaN
Nevada         cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.681333                NaN         NaN             NaN            NaN        NaN      NaN   9.491000   9.860000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN   9.512000   9.628000
New Hampshire  cluster 1     NaN              9.523            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.693167                NaN         NaN           9.116       9.132000        NaN      NaN   9.275500   9.498900
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN   9.150600        NaN
New Jersey     cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.399000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  10.984500
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  10.526000
New Mexico     cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  11.866000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  14.071500
New York       cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.994400                NaN         NaN             NaN       9.268000   9.131000      NaN  12.831000  10.677000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN   9.921500
North Carolina cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  11.552000
North Dakota   cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   8.832667                NaN         NaN             NaN            NaN        NaN      NaN   8.613500   9.307667
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   8.548000                NaN         NaN             NaN            NaN        NaN      NaN        NaN   8.594500
Ohio           cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  12.018000                NaN         NaN             NaN            NaN        NaN  11.3290        NaN  10.231308
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN   9.275000   9.428000
Oklahoma       cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.726000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  10.801000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  12.551000
Oregon         cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN      14.112000        NaN      NaN        NaN   9.896000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  14.549000                NaN         NaN             NaN            NaN        NaN      NaN        NaN        NaN

# Edit Distance

In [158]:
parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(parent_dir)

from dsci_550_a1.unpack_circles import unpack_cluster

haunted_places = "../data/processed/haunted_places_features_added.tab"

df = pd.read_csv(haunted_places, sep = "\t")

clusters = unpack_cluster("../clustering/edit-distance/alcohol/visualization/clusters.json")

cluster_labels = {}  # Create a dictionary to map row indices to cluster labels

for cluster_name, indices in clusters.items():
    for index in indices:
        cluster_labels[index] = cluster_name  # Assign cluster name

# Add the 'Cluster' column
df["Cluster"] = df.index.map(cluster_labels)

### Investigating Edit Distance Clusters

In [161]:
df.groupby(['State', 'Cluster'])[['Total_Deaths', 'Percent_Under_21']].describe()

                         Total_Deaths                     Percent_Under_21
                                count unique     top freq            count unique    top freq
State          Cluster
Alabama        cluster 1            2      1   2,208    2                2      1  3.90%    2
               cluster 2            1      1   2,208    1                1      1  3.90%    1
               cluster 4            2      1   2,208    2                2      1  3.90%    2
Alaska         cluster 1            1      1     433    1                1      1  3.90%    1
               cluster 2            2      1     433    2                2      1  3.90%    2
               cluster 3            4      1     433    4                4      1  3.90%    4
               cluster 4            2      1     433    2                2      1  3.90%    2
               cluster 5            2      1     433    2                2      1  3.90%    2
Arizona        cluster 2            1      1   3,670    1                1      1  2.80%    1
Arkansas       cluster 5            1      1   1,407    1                1      1  3.60%    1
California     cluster 1            2      1  15,443    2                2      1  2.50%    2
               cluster 2            3      1  15,443    3                3      1  2.50%    3
               cluster 3            1      1  15,443    1                1      1  2.50%    1
               cluster 4            6      1  15,443    6                6      1  2.50%    6
               cluster 5            1      1  15,443    1                1      1  2.50%    1
Colorado       cluster 3            3      1   2,623    3                3      1  2.80%    3
               cluster 4            1      1   2,623    1                1      1  2.80%    1
               cluster 5            2      1   2,623    2                2      1  2.80%    2
Connecticut    cluster 1            5      2   1,426    4                5      2  2.20%    4
               cluster 2            4      1   1,426    4                4      1  2.20%    4
               cluster 4            6      2   1,426    5                6      2  2.20%    5
Delaware       cluster 0            1      1     466    1                1      1  2.80%    1
               cluster 1            2      2     466    1                2      2  2.80%    1
               cluster 2            3      1     466    3                3      1  2.80%    3
               cluster 4            5      2     466    3                5      2  2.80%    3
               cluster 5            1      1     466    1                1      1  2.80%    1
Florida        cluster 2            3      2   2,877    2                3      2  3.70%    2
               cluster 3            4      1  10,655    4                4      1  2.30%    4
               cluster 4            9      1  10,655    9                9      1  2.30%    9
               cluster 5            6      2  10,655    5                6      2  2.30%    5
Georgia        cluster 2            1      1   3,953    1                1      1  3.70%    1
               cluster 4            7      1   3,953    7                7      1  3.70%    7
Hawaii         cluster 0            2      2     526    1                2      2  2.30%    1
               cluster 1            3      1     526    3                3      1  2.30%    3
               cluster 2            5      2     526    3                5      2  2.30%    3
               cluster 3            6      2     526    5                6      2  2.30%    5
               cluster 4           31      2     526   26               31      2  2.30%   26
               cluster 5            9      2     526    6                9      2  2.30%    6
Idaho          cluster 1            2      1     732    2                2      1  3.00%    2
               cluster 2            3      2     732    2                3      2  3.00%    2
               cluster 3            5      2     661    3                5      2  1.70%    3
               cluster 4            8      2     732    6                8      2  3.00%    6
               cluster 5            6      2     732    5                6      2  3.00%    5
Illinois       cluster 1            1      1   2,960    1                1      1  3.40%    1
               cluster 2            2      2   2,960    1                2      2  3.40%    1
               cluster 3           10      2   2,960    9               10      2  3.40%    9
               cluster 4           10      2   2,960    7               10      2  3.40%    7
               cluster 5            1      1   2,960    1                1      1  3.40%    1
Indiana        cluster 1            1      1   5,151    1                1      1  3.50%    1
               cluster 2            4      2   2,960    3                4      2  3.40%    3
               cluster 4           11      2   5,151    7               11      2  3.50%    7
Iowa           cluster 1            1      1   1,305    1                1      1  2.50%    1
               cluster 2            3      1   1,305    3                3      1  2.50%    3
               cluster 3            2      1   1,305    2                2      1  2.50%    2
               cluster 4            3      2   1,305    2                3      2  2.50%    2
               cluster 5            1      1   1,305    1                1      1  2.50%    1
Kansas         cluster 2            1      1   1,146    1                1      1  3.10%    1
               cluster 4            2      1   1,146    2                2      1  3.10%    2
Kentucky       cluster 3            4      1   2,206    4                4      1  2.70%    4
               cluster 4            4      2   2,206    3                4      2  2.70%    3
               cluster 5            1      1   2,206    1                1      1  2.70%    1
Louisiana      cluster 1            1      1   2,278    1                1      1  4.10%    1
               cluster 2            1      1   2,278    1                1      1  4.10%    1
Maine          cluster 1            1      1     714    1                1      1  1.70%    1
               cluster 2            4      1     714    4                4      1  1.70%    4
               cluster 3            1      1     714    1                1      1  1.70%    1
               cluster 4           10      1     714   10               10      1  1.70%   10
               cluster 5            4      1     714    4                4      1  1.70%    4
Maryland       cluster 3            2      1   2,482    2                2      1  3.20%    2
               cluster 4            1      1   2,482    1                1      1  3.20%    1
               cluster 5            1      1   2,482    1                1      1  3.20%    1
Massachusetts  cluster 1            3      1   2,760    3                3      1  1.90%    3
               cluster 2            2      1   2,760    2                2      1  1.90%    2
               cluster 4           13      1   2,760   13               13      1  1.90%   13
Michigan       cluster 1            2      1   4,548    2                2      1  2.60%    2
               cluster 2            2      1   4,548    2                2      1  2.60%    2
               cluster 3            5      1   4,548    5                5      1  2.60%    5
               cluster 4           12      1   4,548   12               12      1  2.60%   12
               cluster 5           16      1   4,548   16               16      1  2.60%   16
Minnesota      cluster 4            6      2   2,082    5                6      2  2.30%    5
Mississippi    cluster 2            1      1   1,426    1                1      1  2.20%    1
Missouri       cluster 3            3      1   2,877    3                3      1  3.70%    3
               cluster 4            8      2     466    5                8      2  2.80%    5
               cluster 5            1      1   2,877    1                1      1  3.70%    1
Montana        cluster 4            2      1     605    2                2      1  2.80%    2
               cluster 5            2      2     605    1                2      2  2.80%    1
Nebraska       cluster 1            5      1     720    5                5      1  3.10%    5
               cluster 2           10      1     720   10               10      1  3.10%   10
               cluster 3            3      1     720    3                3      1  3.10%    3
               cluster 4           20      2     720   19               20      2  3.10%   19
               cluster 5            1      1     720    1                1      1  3.10%    1
Nevada         cluster 4            7      1     526    7                7      1  2.30%    7
               cluster 5            3      1     526    3                3      1  2.30%    3
New Hampshire  cluster 1            3      2     661    2                3      2  1.70%    2
               cluster 2            8      3     661    4                8      3  1.70%    4
               cluster 3            2      1     661    2                2      1  1.70%    2
               cluster 4           10      2     661    8               10      2  1.70%    8
               cluster 5            3      3     732    1                3      3  3.00%    1
New Jersey     cluster 3            2      1   3,008    2                2      1  2.20%    2
               cluster 4            3      1   3,008    3                3      1  2.20%    3
               cluster 5            4      1   3,008    4                4      1  2.20%    4
New Mexico     cluster 3            2      1   1,581    2                2      1  2.60%    2
               cluster 5            1      1   3,184    1                1      1  1.80%    1
New York       cluster 2            3      2   6,701    2                3      2  2.00%    2
               cluster 3           10      2   6,701    8               10      2  2.00%    8
               cluster 4           11      2   6,701    7               11      2  2.00%    7
               cluster 5            5      2   2,651    3                5      2  2.30%    3
North Carolina cluster 4            1      1   2,206    1                1      1  2.70%    1
North Dakota   cluster 1            1      1     347    1                1      1  2.60%    1
               cluster 2            1      1     347    1                1      1  2.60%    1
               cluster 3            6      1     347    6                6      1  2.60%    6
               cluster 4            3      1     347    3                3      1  2.60%    3
               cluster 5            2      1     347    2                2      1  2.60%    2
Ohio           cluster 2            2      1   5,739    2                2      1  2.60%    2
               cluster 3            1      1   5,739    1                1      1  2.60%    1
               cluster 4           10      1   5,739   10               10      1  2.60%   10
               cluster 5            6      1   5,739    6                6      1  2.60%    6
Oklahoma       cluster 1            1      1   2,104    1                1      1  2.80%    1
               cluster 3            1      1   2,104    1                1      1  2.80%    1
               cluster 4            1      1   2,104    1                1      1  2.80%    1
               cluster 5            1      1   2,104    1                1      1  2.80%    1
Oregon         cluster 1            2      1   2,186    2                2      1  2.00%    2
               cluster 2            2      1   2,186    2                2      1  2.00%    2
               cluster 4            7      1   2,186    7                7      1  2.00%    7
               cluster 5            1      1   2,186    1                1      1  2.00%    1
Pennsylvania   cluster 1            3      1   5,703    3                3      1  2.70%    3
               cluster 2           11      1   5,703   11               11      1  2.70%   11
               cluster 3            7      1   5,703    7                7      1  2.70%    7
               cluster 4           30      1   5,703   30               30      1  2.70%   30
               cluster 5            9      1   5,703    9                9      1  2.70%    9
Rhode Island   cluster 0            2      1     493    2                2      1  1.40%    2
               cluster 1            1      1   2,623    1                1      1  2.80%    1
               cluster 2            7      1     493    7                7      1  1.40%    7
               cluster 3            2      1     493    2                2      1  1.40%    2
               cluster 4           12      2     493   11               12      2  1.40%   11
               cluster 5            4      1     493    4                4      1  1.40%    4
South Carolina cluster 2            1      1     493    1                1      1  1.40%    1
               cluster 4            5      2     493    3                5      2  1.40%    3
               cluster 5            2      1     493    2                2      1  1.40%    2
South Dakota   cluster 2            8      1     463    8                8      1  3.90%    8
               cluster 3            6      2     463    5                6      1  3.90%    6
               cluster 4            4      1     463    4                4      1  3.90%    4
               cluster 5            3      1     463    3                3      1  3.90%    3
Tennessee      cluster 2            1      1   3,359    1                1      1  2.90%    1
               cluster 4            2      1   3,359    2                2      1  2.90%    2
Texas          cluster 1            4      1  10,647    4                4      1  4.00%    4
               cluster 2            5      2  10,647    4                5      2  4.00%    4
               cluster 3            3      2     605    2                3      2  2.80%    2
               cluster 4           21      3  10,647   15               21      3  4.00%   15
               cluster 5            3      1  10,647    3                3      1  4.00%    3
Utah           cluster 1            3      2     903    2                3      2  3.80%    2
               cluster 2            5      2     903    4                5      2  3.80%    4
               cluster 3            1      1     903    1                1      1  3.80%    1
               cluster 4           44      2     903   39               44      2  3.80%   39
               cluster 5            2      1     903    2                2      1  3.80%    2
Vermont        cluster 1            4      1     332    4                4      1  1.50%    4
               cluster 2            5      1     332    5                5      1  1.50%    5
               cluster 3            3      1     332    3                3      1  1.50%    3
               cluster 4            5      1     332    5                5      1  1.50%    5
               cluster 5            4      2     332    3                4      2  1.50%    3
Virginia       cluster 2            1      1     732    1                1      1  3.00%    1
               cluster 3            1      1     732    1                1      1  3.00%    1
               cluster 4            8      2     732    5                8      2  3.00%    5
               cluster 5            2      1   3,071    2                2      1  3.10%    2
Washington     cluster 2            1      1   3,184    1                1      1  1.80%    1
               cluster 3            2      1   3,184    2                2      1  1.80%    2
               cluster 4            5      2   3,184    4                5      2  1.80%    4
               cluster 5            2      2   3,184    1                2      2  1.80%    1
Washington DC  cluster 2            1      1     347    1                1      1  2.60%    1
               cluster 3            1      1     347    1                1      1  2.60%    1
               cluster 4            3      1     347    3                3      1  2.60%    3
               cluster 5            1      1     347    1                1      1  2.60%    1
West Virginia  cluster 4            1      1   1,037    1                1      1  2.00%    1
Wisconsin      cluster 1            1      1   6,701    1                1      1  2.00%    1
               cluster 2            5      2   6,701    3                5      2  2.00%    3
               cluster 4           11      3   2,651    6               11      3  2.30%    6
               cluster 5            1      1   2,651    1                1      1  2.30%    1
Wyoming        cluster 1            2      1     347    2                2      1  2.60%    2
               cluster 2            5      1     347    5                5      1  2.60%    5
               cluster 3            2      1     347    2                2      1  2.60%    2
               cluster 4            9      3     347    7                9      3  2.60%    7
               cluster 5            7      1     347    7                7      1  2.60%    7

In [163]:
df.groupby(['State', 'Cluster', 'Apparition_Type'])['Time_of_Day'].value_counts(normalize=True).unstack()

Time_of_Day                                           Dusk   Evening   Morning   Unknown
State          Cluster   Apparition_Type
Alabama        cluster 1 Evil Presence                 NaN  1.000000       NaN       NaN
                         Unknown                       NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  1.000000       NaN       NaN
               cluster 4 Unknown                       NaN       NaN       NaN  1.000000
                         Phantom                       NaN       NaN       NaN  1.000000
Alaska         cluster 1 Ghost                         NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN       NaN       NaN  1.000000
                         Female Ghost, Ghost           NaN       NaN       NaN  1.000000
               cluster 3 Unknown                       NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 4 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN       NaN  1.000000
               cluster 5 Spirit                        NaN       NaN       NaN  1.000000
Arizona        cluster 2 Unknown                       NaN       NaN       NaN  1.000000
Arkansas       cluster 5 Unknown                       NaN  1.000000       NaN       NaN
California     cluster 1 Unknown                       NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.666667       NaN  0.333333
               cluster 3 Spirit                        NaN  1.000000       NaN       NaN
               cluster 4 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN  1.000000       NaN       NaN
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 5 Spirit                        NaN       NaN       NaN  1.000000
Colorado       cluster 3 Unknown                       NaN  0.333333  0.333333  0.333333
               cluster 4 Unknown                       NaN  1.000000       NaN       NaN
                         Spirit                        NaN  1.000000       NaN       NaN
               cluster 5 Unknown                       NaN  0.500000       NaN  0.500000
Connecticut    cluster 1 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN  1.000000       NaN       NaN
               cluster 2 Ghost                         NaN       NaN       NaN  1.000000
                         Ghost, Orb                    NaN       NaN       NaN  1.000000
                         Ghost, Spirit                 NaN  1.000000       NaN       NaN
               cluster 4 Unknown                       NaN  0.333333       NaN  0.666667
                         Ghost                         NaN       NaN  0.333333  0.666667
Delaware       cluster 0 Evil Presence, Ghost          NaN  1.000000       NaN       NaN
               cluster 1 Ghost                         NaN  1.000000       NaN       NaN
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  1.000000       NaN       NaN
                         Spirit                        NaN       NaN       NaN  1.000000
                         Ghost, Orb                    NaN       NaN       NaN  1.000000
               cluster 4 Ghost                         NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
                         Orb                           NaN  1.000000       NaN       NaN
               cluster 5 Ghost                         NaN       NaN       NaN  1.000000
Florida        cluster 2 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN  1.000000       NaN       NaN
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 3 Unknown                       NaN  0.500000       NaN  0.500000
               cluster 4 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN  0.333333  0.666667
                         Spirit                        NaN       NaN       NaN  1.000000
                         Orb                           NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN  0.200000       NaN  0.800000
                         Orb                           NaN  1.000000       NaN       NaN
Georgia        cluster 2 Ghost                         NaN  1.000000       NaN       NaN
               cluster 4 Unknown                       NaN  0.285714  0.142857  0.571429
Hawaii         cluster 0 Female Ghost, Ghost           NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 1 Unknown                       NaN  0.666667       NaN  0.333333
               cluster 2 Unknown                       NaN       NaN       NaN  1.000000
               cluster 3 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
               cluster 4 Unknown                       NaN  0.411765  0.058824  0.529412
                         Ghost                         NaN  0.142857       NaN  0.857143
               cluster 5 Unknown                       NaN  0.250000       NaN  0.750000
                         Spirit                        NaN  0.200000  0.200000  0.600000
Idaho          cluster 1 Spirit                        NaN       NaN       NaN  1.000000
               cluster 2 Ghost                         NaN  0.500000       NaN  0.500000
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 3 Unknown                       NaN  0.250000       NaN  0.750000
                         Ghost, Phantom                NaN       NaN       NaN  1.000000
               cluster 4 Unknown                       NaN  1.000000       NaN       NaN
                         Ghost                         NaN  0.666667       NaN  0.333333
                         Spirit                        NaN  0.333333       NaN  0.666667
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN       NaN  0.166667  0.833333
Illinois       cluster 1 Ghost                         NaN       NaN       NaN  1.000000
               cluster 2 Ghost                         NaN       NaN       NaN  1.000000
               cluster 3 Unknown                       NaN  0.111111       NaN  0.888889
                         Ghost                         1.0       NaN       NaN       NaN
               cluster 4 Unknown                       NaN  0.200000       NaN  0.800000
                         Ghost                         NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN  0.500000  0.500000
                         Demon, Spirit                 NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN  1.000000       NaN       NaN
Indiana        cluster 1 Unknown                       NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.333333       NaN  0.666667
                         Spirit                        NaN  1.000000       NaN       NaN
               cluster 4 Unknown                       NaN  0.333333       NaN  0.666667
                         Ghost                         NaN  0.500000       NaN  0.500000
Iowa           cluster 1 Ghost                         NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN  1.000000       NaN       NaN
               cluster 3 Unknown                       NaN       NaN       NaN  1.000000
               cluster 4 Unknown                       NaN  0.500000       NaN  0.500000
                         Orb                           NaN       NaN       NaN  1.000000
               cluster 5 Spirit                        NaN       NaN       NaN  1.000000
Kansas         cluster 2 Unknown                       NaN  1.000000       NaN       NaN
               cluster 4 Unknown                       NaN  0.500000       NaN  0.500000
Kentucky       cluster 3 Unknown                       NaN  0.250000       NaN  0.750000
               cluster 4 Unknown                       NaN  0.333333       NaN  0.666667
                         Ghost                         NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN       NaN       NaN  1.000000
Louisiana      cluster 1 Unknown                       NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  1.000000       NaN       NaN
Maine          cluster 1 Spirit                        NaN       NaN       NaN  1.000000
               cluster 2 Ghost                         NaN       NaN       NaN  1.000000
                         Ghost, Spirit                 NaN  0.500000       NaN  0.500000
               cluster 3 Unknown                       NaN       NaN       NaN  1.000000
               cluster 4 Ghost                         NaN       NaN  0.250000  0.750000
                         Spirit                        NaN  0.333333  0.333333  0.333333
                         Ghost, Orb                    NaN       NaN       NaN  1.000000
                         Orb                           NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN  0.250000       NaN  0.750000
Maryland       cluster 3 Unknown                       NaN  0.500000       NaN  0.500000
               cluster 4 Ghost                         NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN       NaN       NaN  1.000000
Massachusetts  cluster 1 Unknown                       NaN  0.500000  0.500000       NaN
                         Ghost                         NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN       NaN  1.000000
               cluster 4 Unknown                       NaN  0.222222       NaN  0.777778
                         Ghost                         NaN       NaN  0.333333  0.666667
                         Spirit                        NaN       NaN       NaN  1.000000
Michigan       cluster 1 Spirit                        NaN  1.000000       NaN       NaN
                         Demon, Ghost, Orb             NaN       NaN       NaN  1.000000
               cluster 2 Ghost                         NaN  0.500000       NaN  0.500000
               cluster 3 Unknown                       NaN  0.400000       NaN  0.600000
               cluster 4 Unknown                       NaN  0.250000  0.125000  0.625000
                         Ghost                         NaN  0.333333  0.333333  0.333333
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN  0.285714       NaN  0.714286
                         Phantom                       NaN  1.000000       NaN       NaN
                         Orb                           NaN       NaN       NaN  1.000000
Minnesota      cluster 4 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN  0.500000       NaN  0.500000
Mississippi    cluster 2 Unknown                       NaN       NaN       NaN  1.000000
Missouri       cluster 3 Unknown                       NaN  0.333333       NaN  0.666667
               cluster 4 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN       NaN       NaN  1.000000
                         Spirit                        NaN  1.000000       NaN       NaN
                         Orb                           NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN  1.000000       NaN       NaN
Montana        cluster 4 Spirit                        NaN  1.000000       NaN       NaN
                         Ghost, Spirit                 NaN  1.000000       NaN       NaN
               cluster 5 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN       NaN  1.000000
Nebraska       cluster 1 Unknown                       NaN       NaN  0.333333  0.666667
                         Phantom                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN       NaN  1.000000
               cluster 2 Unknown                       NaN  0.500000       NaN  0.500000
                         Phantom                       NaN  1.000000       NaN       NaN
                         Spirit                        NaN       NaN       NaN  1.000000
                         Female Ghost, Ghost, Spirit   NaN       NaN       NaN  1.000000
                         Floating Light, Ghost         NaN  1.000000       NaN       NaN
               cluster 3 Ghost                         NaN       NaN       NaN  1.000000
               cluster 4 Unknown                       NaN  0.428571       NaN  0.571429
                         Ghost                         NaN  0.500000  0.125000  0.375000
                         Spirit                        NaN       NaN  0.666667  0.333333
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
               cluster 5 Ghost                         NaN  1.000000       NaN       NaN
Nevada         cluster 4 Unknown                       NaN  0.666667       NaN  0.333333
                         Ghost                         NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
New Hampshire  cluster 1 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN  0.500000       NaN  0.500000
               cluster 2 Unknown                       NaN  0.800000       NaN  0.200000
                         Ghost, Spirit                 NaN       NaN       NaN  1.000000
                         Ghost, Phantom                NaN       NaN       NaN  1.000000
                         Demon, Ghost, Orb             NaN       NaN       NaN  1.000000
               cluster 3 Spirit                        NaN  0.500000       NaN  0.500000
               cluster 4 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN  0.250000       NaN  0.750000
                         Spirit                        NaN  0.500000       NaN  0.500000
               cluster 5 Spirit                        NaN       NaN       NaN  1.000000
New Jersey     cluster 3 Unknown                       NaN       NaN       NaN  1.000000
               cluster 4 Unknown                       NaN  0.333333       NaN  0.666667
               cluster 5 Unknown                       NaN  0.333333       NaN  0.666667
                         Ghost                         NaN       NaN       NaN  1.000000
New Mexico     cluster 3 Unknown                       NaN  1.000000       NaN       NaN
                         Ghost                         NaN  1.000000       NaN       NaN
               cluster 5 Unknown                       NaN       NaN       NaN  1.000000
New York       cluster 2 Ghost                         NaN       NaN       NaN  1.000000
                         Spirit                        NaN  0.500000       NaN  0.500000
               cluster 3 Unknown                       NaN  0.400000       NaN  0.600000
               cluster 4 Unknown                       NaN  0.500000       NaN  0.500000
                         Ghost                         NaN  0.250000       NaN  0.750000
                         Spirit                        NaN       NaN       NaN  1.000000
                         Ghost, Spirit                 NaN  1.000000       NaN       NaN
                         Orb                           NaN  1.000000       NaN       NaN
               cluster 5 Unknown                       NaN  0.200000  0.200000  0.600000
North Carolina cluster 4 Unknown                       NaN       NaN       NaN  1.000000
North Dakota   cluster 1 Spirit                        NaN  1.000000       NaN       NaN
               cluster 2 Spirit                        NaN       NaN       NaN  1.000000
               cluster 3 Unknown                       NaN  1.000000       NaN       NaN
                         Ghost                         NaN  0.666667  0.333333       NaN
               cluster 4 Unknown                       NaN       NaN  0.500000  0.500000
                         Ghost                         NaN  1.000000       NaN       NaN
               cluster 5 Unknown                       NaN       NaN       NaN  1.000000
                         Ghost                         NaN       NaN       NaN  1.000000
Ohio           cluster 2 Unknown                       NaN  1.000000       NaN       NaN
               cluster 3 Unknown                       NaN       NaN       NaN  1.000000
               cluster 4 Unknown                       NaN  0.571429       NaN  0.428571
                         Ghost                         NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN  0.250000       NaN  0.750000
                         Phantom                       NaN  1.000000       NaN       NaN
                         Spirit                        NaN       NaN       NaN  1.000000
Oklahoma       cluster 1 Ghost                         NaN  1.000000       NaN       NaN
               cluster 3 Unknown                       NaN       NaN       NaN  1.000000
               cluster 4 Unknown                       NaN       NaN       NaN  1.000000
               cluster 5 Unknown                       NaN       NaN       NaN  1.000000
Oregon         cluster 1 Unknown                       NaN  0.500000       NaN  0.500000
               cluster 2 Unknown                       NaN  0.500000       NaN  0.500000
               cluster 4 Unknown                       NaN  0.200000       NaN  0.800000
                         Ghost                         NaN  1.000000       NaN       NaN
                         Ghost, Spirit                 NaN  1.000000       NaN       NaN
               cluster 5 Ghost                         NaN       NaN       NaN  1.000000
Pennsylvania   cluster 1 Unknown                       NaN  1.000000       NaN       NaN
               cluster 2 Unknown                       NaN       NaN       NaN  1.000000
                         Phantom                       NaN       NaN       NaN  1.000000
                         Spirit                        NaN       NaN       NaN  1.000000
               cluster 3 Ghost                         NaN  0.166667  0.166667  0.666667

In [165]:
df.groupby(['State', 'Cluster']).size().unstack(fill_value=0)

Cluster         cluster 0  cluster 1  cluster 2  cluster 3  cluster 4  cluster 5
State
Alabama                 0          2          1          0          2          0
Alaska                  0          1          2          4          2          2
Arizona                 0          0          1          0          0          0
Arkansas                0          0          0          0          0          1
California              0          2          3          1          6          1
Colorado                0          0          0          3          2          2
Connecticut             0          5          4          0          6          0
Delaware                1          2          3          0          5          1
Florida                 0          0          3          4          9          6
Georgia                 0          0          1          0          7          0
Hawaii                  2          3          5          6         31          9
Idaho                   0          2          3          5          8          6
Illinois                0          1          2         10         10          1
Indiana                 0          1          4          0         11          0
Iowa                    0          1          3          2          3          1
Kansas                  0          0          1          0          2          0
Kentucky                0          0          0          4          4          1
Louisiana               0          1          1          0          0          0
Maine                   0          1          4          1         10          4
Maryland                0          0          0          2          1          1
Massachusetts           0          3          2          0         13          0
Michigan                0          2          2          5         12         16
Minnesota               0          0          0          0          6          0
Mississippi             0          0          1          0          0          0
Missouri                0          0          0          3          8          1
Montana                 0          0          0          0          2          2
Nebraska                0          5         10          3         20          1
Nevada                  0          0          0          0          7          3
New Hampshire           0          3          8          2         10          3
New Jersey              0          0          0          2          3          4
New Mexico              0          0          0          2          0          1
New York                0          0          3         10         11          5
North Carolina          0          0          0          0          1          0
North Dakota            0          1          1          6          3          2
Ohio                    0          0          2          1         10          6
Oklahoma                0          1          0          1          1          1
Oregon                  0          2          2          0          7          1
Pennsylvania            0          3         11          7         30          9
Rhode Island            2          1          7          2         12          4
South Carolina          0          0          1          0          5          2
South Dakota            0          0          8          6          4          3
Tennessee               0          0          1          0          2          0
Texas                   0          4          5          3         21          3
Utah                    0          3          5          1         44          2
Vermont                 0          4          5          3          5          4
Virginia                0          0          1          1          8          2
Washington              0          0          1          2          5          2
Washington DC           0          0          1          1          3          1
West Virginia           0          0          0          0          1          0
Wisconsin               0          1          5          0         11          1
Wyoming                 0          2          5          2          9          7

In [167]:
df.pivot_table(index=['State', 'Cluster'], columns='Apparition_Type', values='Daylight_Duration_Hours', aggfunc='mean')

Apparition_Type            Demon  Demon, Ghost, Orb  Demon, Spirit  Evil Presence  Evil Presence, Ghost  Female Ghost, Ghost  Female Ghost, Ghost, Spirit  Floating Light  Floating Light, Ghost      Ghost  Ghost, Male Ghost  Ghost, Orb  Ghost, Phantom  Ghost, Spirit      Orb  Phantom     Spirit    Unknown
State          Cluster
Alabama        cluster 1     NaN                NaN            NaN         13.527                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  10.536000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  10.558000
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN  13.5090        NaN  13.468000
Alaska         cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   4.173000                NaN         NaN             NaN            NaN      NaN      NaN        NaN        NaN
               cluster 2     NaN                NaN            NaN            NaN                   NaN               5.7880                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN   6.013000
               cluster 3     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN   5.897000   5.895000
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   5.799000                NaN         NaN             NaN            NaN      NaN      NaN        NaN   4.203000
               cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN   5.748500        NaN
Arizona        cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  13.454000
Arkansas       cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  14.317000
California     cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  10.326000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  12.661333
               cluster 3     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN  14.039000        NaN
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.612000                NaN         NaN             NaN            NaN      NaN      NaN   9.221000  11.419250
               cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN  11.074000        NaN
Colorado       cluster 3     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  12.875667
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN  11.504000   9.457000
               cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  12.958000
Connecticut    cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.272000                NaN         NaN             NaN            NaN      NaN      NaN        NaN   9.260750
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.303000                NaN       9.259             NaN      12.198000      NaN      NaN        NaN        NaN
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.889333                NaN         NaN             NaN            NaN      NaN      NaN        NaN  12.508667
Delaware       cluster 0     NaN                NaN            NaN            NaN                 9.478                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN        NaN
               cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.465000                NaN         NaN             NaN            NaN      NaN      NaN   9.488000        NaN
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN       9.490             NaN            NaN      NaN      NaN   9.477000  11.402000
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.248000                NaN         NaN             NaN            NaN   9.5110      NaN   9.396500        NaN
               cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.849000                NaN         NaN             NaN            NaN      NaN      NaN        NaN        NaN
Florida        cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.682000                NaN         NaN             NaN            NaN      NaN      NaN  10.607000  10.666000
               cluster 3     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  11.350250
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  11.029000                NaN         NaN             NaN            NaN  11.2580      NaN  10.541000  10.583000
               cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN  10.5410      NaN        NaN  11.249200
Georgia        cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.492000                NaN         NaN             NaN            NaN      NaN      NaN        NaN        NaN
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  12.491286
Hawaii         cluster 0     NaN                NaN            NaN            NaN                   NaN              10.9000                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN  10.938000        NaN
               cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  10.957333
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  11.062200
               cluster 3     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN      10.891500      NaN      NaN        NaN  11.428750
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.913929                NaN         NaN             NaN            NaN      NaN      NaN        NaN  10.954647
               cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN  11.339200  11.538750
Idaho          cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN   9.108500        NaN
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   8.853500                NaN         NaN             NaN            NaN      NaN      NaN   9.065000        NaN
               cluster 3     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN          10.362            NaN      NaN      NaN        NaN   9.112500
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.653333                NaN         NaN             NaN       9.145000      NaN      NaN   8.998333   9.191000
               cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  10.833000
Illinois       cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.372000                NaN         NaN             NaN            NaN      NaN      NaN        NaN        NaN
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.563500                NaN         NaN             NaN            NaN      NaN      NaN        NaN        NaN
               cluster 3     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.433000                NaN         NaN             NaN            NaN      NaN      NaN        NaN  10.350333
               cluster 4     NaN                NaN          9.211            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.258000                NaN         NaN             NaN            NaN      NaN      NaN   9.313500  11.380800
               cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN   9.251000
Indiana        cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN   9.462000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN  14.403000  10.923000
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.406000                NaN         NaN             NaN            NaN      NaN      NaN        NaN  11.121444
Iowa           cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.267000                NaN         NaN             NaN            NaN      NaN      NaN        NaN        NaN
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  15.305000                NaN         NaN             NaN            NaN      NaN      NaN        NaN  11.724000
               cluster 3     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN   9.211500
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN  15.1590      NaN        NaN   9.230500
               cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN  14.382000        NaN
Kansas         cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  11.385000
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  11.670000
Kentucky       cluster 3     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  13.857500
               cluster 4     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.757000                NaN         NaN             NaN            NaN      NaN      NaN        NaN  14.106000
               cluster 5     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  13.762000
Louisiana      cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  13.506000
               cluster 2     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN        NaN  10.544000
Maine          cluster 1     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN      NaN      NaN   9.012000        NaN

# Cosine Similarity

In [169]:
parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(parent_dir)

from dsci_550_a1.unpack_circles import unpack_cluster

haunted_places = "../data/processed/haunted_places_features_added.tab"

df = pd.read_csv(haunted_places, sep = "\t")

clusters = unpack_cluster("../clustering/cosine/alcohol/visualization/clusters.json")

cluster_labels = {}  # Create a dictionary to map row indices to cluster labels

for cluster_name, indices in clusters.items():
    for index in indices:
        cluster_labels[index] = cluster_name  # Assign cluster name

# Add the 'Cluster' column
df["Cluster"] = df.index.map(cluster_labels)

### Investigating Cosine Clusters

In [172]:
df.groupby(['State', 'Cluster'])[['Total_Deaths', 'Percent_Under_21']].describe()

                         Total_Deaths                     Percent_Under_21
                                count unique     top freq            count unique    top freq
State          Cluster
Alabama        cluster 0            5      1   2,208    5                5      1  3.90%    5
Alaska         cluster 0           11      1     433   11               11      1  3.90%   11
Arizona        cluster 0            1      1   3,670    1                1      1  2.80%    1
Arkansas       cluster 0            1      1   1,407    1                1      1  3.60%    1
California     cluster 0           13      1  15,443   13               13      1  2.50%   13
Colorado       cluster 0            6      1   2,623    6                6      1  2.80%    6
Connecticut    cluster 0           15      2   1,426   13               15      2  2.20%   13
Delaware       cluster 0           12      2     466    9               12      2  2.80%    9
Florida        cluster 0           22      2  10,655   19               22      2  2.30%   19
Georgia        cluster 0            8      1   3,953    8                8      1  3.70%    8
Hawaii         cluster 0           56      2     526   44               56      2  2.30%   44
Idaho          cluster 0           24      2     732   17               24      2  3.00%   17
Illinois       cluster 0           24      2   2,960   19               24      2  3.40%   19
Indiana        cluster 0           16      2   5,151    9               16      2  3.50%    9
Iowa           cluster 0           10      2   1,305    9               10      2  2.50%    9
Kansas         cluster 0            3      1   1,146    3                3      1  3.10%    3
Kentucky       cluster 0            9      2   2,206    8                9      2  2.70%    8
Louisiana      cluster 0            2      1   2,278    2                2      1  4.10%    2
Maine          cluster 0           20      1     714   20               20      1  1.70%   20
Maryland       cluster 0            4      1   2,482    4                4      1  3.20%    4
Massachusetts  cluster 0           18      1   2,760   18               18      1  1.90%   18
Michigan       cluster 0           37      1   4,548   37               37      1  2.60%   37
Minnesota      cluster 0            6      2   2,082    5                6      2  2.30%    5
Mississippi    cluster 0            1      1   1,426    1                1      1  2.20%    1
Missouri       cluster 0           12      2   2,877    7               12      2  3.70%    7
Montana        cluster 0            4      2     605    3                4      2  2.80%    3
Nebraska       cluster 0           39      2     720   38               39      2  3.10%   38
Nevada         cluster 0           10      1     526   10               10      1  2.30%   10
New Hampshire  cluster 0           26      3     661   17               26      3  1.70%   17
New Jersey     cluster 0            9      1   3,008    9                9      1  2.20%    9
New Mexico     cluster 0            3      2   1,581    2                3      2  2.60%    2
New York       cluster 0           29      2   6,701   19               29      2  2.00%   19
North Carolina cluster 0            1      1   2,206    1                1      1  2.70%    1
North Dakota   cluster 0           13      1     347   13               13      1  2.60%   13
Ohio           cluster 0           19      1   5,739   19               19      1  2.60%   19
Oklahoma       cluster 0            4      1   2,104    4                4      1  2.80%    4
Oregon         cluster 0           12      1   2,186   12               12      1  2.00%   12
Pennsylvania   cluster 0           60      1   5,703   60               60      1  2.70%   60
Rhode Island   cluster 0           28      2     493   26               28      2  1.40%   26
South Carolina cluster 0            8      2     493    6                8      2  1.40%    6
South Dakota   cluster 0           21      2     463   20               21      1  3.90%   21
Tennessee      cluster 0            3      1   3,359    3                3      1  2.90%    3
Texas          cluster 0           36      3  10,647   27               36      3  4.00%   27
Utah           cluster 0           55      2     903   48               55      2  3.80%   48
Vermont        cluster 0           21      2     332   20               21      2  1.50%   20
Virginia       cluster 0           12      2     732    7               12      2  3.00%    7
Washington     cluster 0           10      2   3,184    8               10      2  1.80%    8
Washington DC  cluster 0            6      1     347    6                6      1  2.60%    6
West Virginia  cluster 0            1      1   1,037    1                1      1  2.00%    1
Wisconsin      cluster 0           18      3   2,651    9               18      3  2.30%    9
Wyoming        cluster 0           25      3     347   23               25      3  2.60%   23

In [174]:
df.groupby(['State', 'Cluster', 'Apparition_Type'])['Time_of_Day'].value_counts(normalize=True).unstack()

Time_of_Day                                               Dusk   Evening   Morning   Unknown
State          Cluster   Apparition_Type
Alabama        cluster 0 Evil Presence                     NaN  1.000000       NaN       NaN
                         Phantom                           NaN       NaN       NaN  1.000000
                         Unknown                           NaN  0.333333       NaN  0.666667
Alaska         cluster 0 Unknown                           NaN       NaN       NaN  1.000000
                         Female Ghost, Ghost               NaN       NaN       NaN  1.000000
                         Ghost                             NaN       NaN       NaN  1.000000
                         Spirit                            NaN       NaN       NaN  1.000000
Arizona        cluster 0 Unknown                           NaN       NaN       NaN  1.000000
Arkansas       cluster 0 Unknown                           NaN  1.000000       NaN       NaN
California     cluster 0 Unknown                           NaN  0.444444       NaN  0.555556
                         Ghost                             NaN  1.000000       NaN       NaN
                         Spirit                            NaN  0.333333       NaN  0.666667
Colorado       cluster 0 Unknown                           NaN  0.500000  0.166667  0.333333
                         Spirit                            NaN  1.000000       NaN       NaN
Connecticut    cluster 0 Unknown                           NaN  0.428571       NaN  0.571429
                         Ghost                             NaN  0.200000  0.200000  0.600000
                         Ghost, Orb                        NaN       NaN       NaN  1.000000
                         Ghost, Spirit                     NaN  1.000000       NaN       NaN
Delaware       cluster 0 Unknown                           NaN  1.000000       NaN       NaN
                         Ghost                             NaN  0.250000       NaN  0.750000
                         Spirit                            NaN       NaN       NaN  1.000000
                         Ghost, Orb                        NaN       NaN       NaN  1.000000
                         Evil Presence, Ghost              NaN  1.000000       NaN       NaN
                         Orb                               NaN  1.000000       NaN       NaN
Florida        cluster 0 Unknown                           NaN  0.230769       NaN  0.769231
                         Ghost                             NaN  0.250000  0.250000  0.500000
                         Spirit                            NaN       NaN       NaN  1.000000
                         Orb                               NaN  0.333333       NaN  0.666667
Georgia        cluster 0 Unknown                           NaN  0.285714  0.142857  0.571429
                         Ghost                             NaN  1.000000       NaN       NaN
Hawaii         cluster 0 Unknown                           NaN  0.363636  0.030303  0.606061
                         Female Ghost, Ghost               NaN       NaN       NaN  1.000000
                         Ghost                             NaN  0.142857       NaN  0.857143
                         Spirit                            NaN  0.166667  0.166667  0.666667
                         Ghost, Spirit                     NaN       NaN       NaN  1.000000
Idaho          cluster 0 Unknown                           NaN  0.181818  0.090909  0.727273
                         Ghost                             NaN  0.600000       NaN  0.400000
                         Spirit                            NaN  0.166667       NaN  0.833333
                         Ghost, Spirit                     NaN       NaN       NaN  1.000000
                         Ghost, Phantom                    NaN       NaN       NaN  1.000000
Illinois       cluster 0 Unknown                           NaN  0.200000       NaN  0.800000
                         Ghost                        0.166667       NaN       NaN  0.833333
                         Spirit                            NaN       NaN  0.500000  0.500000
                         Demon, Spirit                     NaN       NaN       NaN  1.000000
Indiana        cluster 0 Unknown                           NaN  0.307692       NaN  0.692308
                         Ghost                             NaN  0.500000       NaN  0.500000
                         Spirit                            NaN  1.000000       NaN       NaN
Iowa           cluster 0 Unknown                           NaN  0.333333       NaN  0.666667
                         Ghost                             NaN  0.500000       NaN  0.500000
                         Spirit                            NaN       NaN       NaN  1.000000
                         Orb                               NaN       NaN       NaN  1.000000
Kansas         cluster 0 Unknown                           NaN  0.666667       NaN  0.333333
Kentucky       cluster 0 Unknown                           NaN  0.250000       NaN  0.750000
                         Ghost                             NaN       NaN       NaN  1.000000
Louisiana      cluster 0 Unknown                           NaN  0.500000       NaN  0.500000
Maine          cluster 0 Unknown                           NaN  0.200000       NaN  0.800000
                         Ghost                             NaN       NaN  0.166667  0.833333
                         Spirit                            NaN  0.250000  0.250000  0.500000
                         Ghost, Orb                        NaN       NaN       NaN  1.000000
                         Ghost, Spirit                     NaN  0.500000       NaN  0.500000
                         Orb                               NaN       NaN       NaN  1.000000
Maryland       cluster 0 Unknown                           NaN  0.333333       NaN  0.666667
                         Ghost                             NaN       NaN       NaN  1.000000
Massachusetts  cluster 0 Unknown                           NaN  0.250000  0.083333  0.666667
                         Ghost                             NaN       NaN  0.200000  0.800000
                         Spirit                            NaN       NaN       NaN  1.000000
Michigan       cluster 0 Phantom                           NaN  1.000000       NaN       NaN
                         Unknown                           NaN  0.296296  0.037037  0.666667
                         Ghost                             NaN  0.400000  0.200000  0.400000
                         Spirit                            NaN  0.500000       NaN  0.500000
                         Orb                               NaN       NaN       NaN  1.000000
                         Demon, Ghost, Orb                 NaN       NaN       NaN  1.000000
Minnesota      cluster 0 Unknown                           NaN  0.500000       NaN  0.500000
                         Ghost                             NaN  0.500000       NaN  0.500000
Mississippi    cluster 0 Unknown                           NaN       NaN       NaN  1.000000
Missouri       cluster 0 Unknown                           NaN  0.500000       NaN  0.500000
                         Ghost                             NaN       NaN       NaN  1.000000
                         Spirit                            NaN  1.000000       NaN       NaN
                         Orb                               NaN       NaN       NaN  1.000000
Montana        cluster 0 Unknown                           NaN       NaN       NaN  1.000000
                         Ghost                             NaN       NaN       NaN  1.000000
                         Spirit                            NaN  1.000000       NaN       NaN
                         Ghost, Spirit                     NaN  1.000000       NaN       NaN
Nebraska       cluster 0 Phantom                           NaN  0.500000       NaN  0.500000
                         Unknown                           NaN  0.375000  0.062500  0.562500
                         Ghost                             NaN  0.384615  0.076923  0.538462
                         Spirit                            NaN       NaN  0.500000  0.500000
                         Ghost, Spirit                     NaN       NaN       NaN  1.000000
                         Female Ghost, Ghost, Spirit       NaN       NaN       NaN  1.000000
                         Floating Light, Ghost             NaN  1.000000       NaN       NaN
Nevada         cluster 0 Unknown                           NaN  0.400000       NaN  0.600000
                         Ghost                             NaN       NaN       NaN  1.000000
                         Spirit                            NaN       NaN       NaN  1.000000
New Hampshire  cluster 0 Unknown                           NaN  0.400000       NaN  0.600000
                         Ghost                             NaN  0.333333       NaN  0.666667
                         Spirit                            NaN  0.285714       NaN  0.714286
                         Ghost, Spirit                     NaN       NaN       NaN  1.000000
                         Ghost, Phantom                    NaN       NaN       NaN  1.000000
                         Demon, Ghost, Orb                 NaN       NaN       NaN  1.000000
New Jersey     cluster 0 Unknown                           NaN  0.250000       NaN  0.750000
                         Ghost                             NaN       NaN       NaN  1.000000
New Mexico     cluster 0 Unknown                           NaN  0.500000       NaN  0.500000
                         Ghost                             NaN  1.000000       NaN       NaN
New York       cluster 0 Unknown                           NaN  0.368421  0.052632  0.578947
                         Ghost                             NaN  0.200000       NaN  0.800000
                         Spirit                            NaN  0.333333       NaN  0.666667
                         Ghost, Spirit                     NaN  1.000000       NaN       NaN
                         Orb                               NaN  1.000000       NaN       NaN
North Carolina cluster 0 Unknown                           NaN       NaN       NaN  1.000000
North Dakota   cluster 0 Unknown                           NaN  0.500000  0.166667  0.333333
                         Ghost                             NaN  0.600000  0.200000  0.200000
                         Spirit                            NaN  0.500000       NaN  0.500000
Ohio           cluster 0 Phantom                           NaN  1.000000       NaN       NaN
                         Unknown                           NaN  0.500000       NaN  0.500000
                         Ghost                             NaN       NaN       NaN  1.000000
                         Spirit                            NaN       NaN       NaN  1.000000
Oklahoma       cluster 0 Unknown                           NaN       NaN       NaN  1.000000
                         Ghost                             NaN  1.000000       NaN       NaN
Oregon         cluster 0 Unknown                           NaN  0.333333       NaN  0.666667
                         Ghost                             NaN  0.500000       NaN  0.500000
                         Ghost, Spirit                     NaN  1.000000       NaN       NaN
Pennsylvania   cluster 0 Phantom                           NaN       NaN  0.333333  0.666667
                         Unknown                           NaN  0.250000       NaN  0.750000
                         Ghost                             NaN  0.117647  0.058824  0.823529
                         Spirit                            NaN       NaN       NaN  1.000000
                         Orb                               NaN       NaN       NaN  1.000000
Rhode Island   cluster 0 Unknown                           NaN  0.142857  0.142857  0.714286
                         Ghost                             NaN  0.400000       NaN  0.600000
                         Spirit                            NaN       NaN  0.142857  0.857143
                         Ghost, Spirit                     NaN  0.400000       NaN  0.600000
                         Orb                               NaN       NaN       NaN  1.000000
                         Ghost, Phantom                    NaN       NaN       NaN  1.000000
                         Demon                             NaN  1.000000       NaN       NaN
                         Ghost, Male Ghost                 NaN       NaN       NaN  1.000000
South Carolina cluster 0 Phantom                           NaN       NaN       NaN  1.000000
                         Unknown                           NaN  0.500000       NaN  0.500000
                         Ghost                             NaN  1.000000       NaN       NaN
                         Spirit                            NaN       NaN       NaN  1.000000
                         Orb                               NaN       NaN       NaN  1.000000
South Dakota   cluster 0 Phantom                           NaN  1.000000       NaN       NaN
                         Unknown                           NaN  0.400000       NaN  0.600000
                         Ghost                             NaN  0.750000       NaN  0.250000
                         Spirit                            NaN       NaN       NaN  1.000000
                         Ghost, Orb                        NaN       NaN       NaN  1.000000
                         Ghost, Spirit                     NaN  0.333333       NaN  0.666667
                         Orb                               NaN       NaN       NaN  1.000000
                         Floating Light                    NaN       NaN       NaN  1.000000
Tennessee      cluster 0 Unknown                           NaN       NaN       NaN  1.000000
                         Ghost                             NaN       NaN       NaN  1.000000
Texas          cluster 0 Unknown                           NaN  0.473684       NaN  0.526316
                         Ghost                             NaN  0.583333  0.083333  0.333333
                         Spirit                            NaN       NaN       NaN  1.000000
                         Ghost, Phantom                    NaN       NaN       NaN  1.000000
                         Demon                             NaN       NaN       NaN  1.000000
Utah           cluster 0 Evil Presence                     NaN  0.333333       NaN  0.666667
                         Unknown                           NaN  0.083333  0.083333  0.833333
                         Ghost                             NaN  0.235294  0.058824  0.705882
                         Spirit                            NaN  0.333333       NaN  0.666667
                         Ghost, Orb                        NaN       NaN       NaN  1.000000
                         Ghost, Spirit                     NaN       NaN       NaN  1.000000
                         Orb                               NaN  0.333333       NaN  0.666667
Vermont        cluster 0 Evil Presence                     NaN  1.000000       NaN       NaN
                         Unknown                           NaN  0.250000       NaN  0.750000
                         Female Ghost, Ghost               NaN  0.500000       NaN  0.500000
                         Ghost                             NaN  0.500000       NaN  0.500000
                         Spirit                            NaN  1.000000       NaN       NaN
                         Ghost, Orb                        NaN       NaN       NaN  1.000000
                         Orb                               NaN       NaN       NaN  1.000000
                         Ghost, Phantom                    NaN       NaN       NaN  1.000000
Virginia       cluster 0 Unknown                           NaN       NaN  0.200000  0.800000
                         Ghost                             NaN  0.166667       NaN  0.833333
                         Spirit                            NaN  1.000000       NaN       NaN
Washington     cluster 0 Unknown                           NaN  0.125000       NaN  0.875000
                         Orb                               NaN  0.500000       NaN  0.500000
Washington DC  cluster 0 Ghost                             NaN  0.250000       NaN  0.750000
                         Spirit                            NaN  0.500000       NaN  0.500000
West Virginia  cluster 0 Unknown                           NaN       NaN       NaN  1.000000
Wisconsin      cluster 0 Unknown                           NaN  0.307692       NaN  0.692308
                         Ghost                             NaN       NaN       NaN  1.000000
                         Spirit                            NaN       NaN       NaN  1.000000
                         Orb                               NaN       NaN       NaN  1.000000
                         Demon, Spirit                     NaN       NaN       NaN  1.000000
Wyoming        cluster 0 Phantom                           NaN       NaN       NaN  1.000000
                         Unknown                           NaN  0.285714  0.142857  0.571429
                         Female Ghost, Ghost               NaN       NaN       NaN  1.000000
                         Ghost                        0.142857  0.285714       NaN  0.571429
                         Spirit                            NaN  0.428571  0.285714  0.285714
                         Ghost, Spirit                     NaN       NaN       NaN  1.000000
                         Floating Light                    NaN  1.000000       NaN       NaN

In [176]:
df.groupby(['State', 'Cluster']).size().unstack(fill_value=0)

Cluster         cluster 0
State
Alabama                 5
Alaska                 11
Arizona                 1
Arkansas                1
California             13
Colorado                7
Connecticut            15
Delaware               12
Florida                22
Georgia                 8
Hawaii                 56
Idaho                  24
Illinois               24
Indiana                16
Iowa                   10
Kansas                  3
Kentucky                9
Louisiana               2
Maine                  20
Maryland                4
Massachusetts          18
Michigan               37
Minnesota               6
Mississippi             1
Missouri               12
Montana                 4
Nebraska               39
Nevada                 10
New Hampshire          26
New Jersey              9
New Mexico              3
New York               29
North Carolina          1
North Dakota           13
Ohio                   19
Oklahoma                4
Oregon                 12
Pennsylvania           60
Rhode Island           28
South Carolina          8
South Dakota           21
Tennessee               3
Texas                  36
Utah                   55
Vermont                21
Virginia               12
Washington             10
Washington DC           6
West Virginia           1
Wisconsin              18
Wyoming                25

In [178]:
df.pivot_table(index=['State', 'Cluster'], columns='Apparition_Type', values='Daylight_Duration_Hours', aggfunc='mean')

Apparition_Type            Demon  Demon, Ghost, Orb  Demon, Spirit  Evil Presence  Evil Presence, Ghost  Female Ghost, Ghost  Female Ghost, Ghost, Spirit  Floating Light  Floating Light, Ghost      Ghost  Ghost, Male Ghost  Ghost, Orb  Ghost, Phantom  Ghost, Spirit        Orb  Phantom     Spirit    Unknown
State          Cluster
Alabama        cluster 0     NaN                NaN            NaN      13.527000                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN  13.5090        NaN  11.520667
Alaska         cluster 0     NaN                NaN            NaN            NaN                   NaN               5.7880                          NaN             NaN                    NaN   4.986000                NaN         NaN             NaN            NaN        NaN      NaN   5.822750   5.501500
Arizona        cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  13.454000
Arkansas       cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  14.317000
California     cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.612000                NaN         NaN             NaN            NaN        NaN      NaN  11.444667  11.590333
Colorado       cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN  11.504000  12.333333
Connecticut    cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.248600                NaN       9.259             NaN      12.198000        NaN      NaN        NaN  10.652714
Delaware       cluster 0     NaN                NaN            NaN            NaN                 9.478                  NaN                          NaN             NaN                    NaN   9.452500                NaN       9.490             NaN            NaN   9.511000      NaN   9.439500  11.402000
Florida        cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.942250                NaN         NaN             NaN            NaN  11.019000      NaN  10.574000  11.081692
Georgia        cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.492000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  12.491286
Hawaii         cluster 0     NaN                NaN            NaN            NaN                   NaN              10.9000                          NaN             NaN                    NaN  10.913929                NaN         NaN             NaN      10.891500        NaN      NaN  11.272333  11.099455
Idaho          cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.933400                NaN         NaN          10.362       9.145000        NaN      NaN   9.046167  10.058091
Illinois       cluster 0     NaN                NaN          9.211            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.741333                NaN         NaN             NaN            NaN        NaN      NaN   9.313500  10.620533
Indiana        cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.406000                NaN         NaN             NaN            NaN        NaN      NaN  14.403000  10.948000
Iowa           cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  12.286000                NaN         NaN             NaN            NaN  15.159000      NaN  14.382000  10.055333
Kansas         cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  11.575000
Kentucky       cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.757000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  13.938750
Louisiana      cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  12.025000
Maine          cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.013000                NaN       8.965             NaN       8.998500   9.046500      NaN   8.823500   9.084200
Maryland       cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.478000                NaN         NaN             NaN            NaN        NaN      NaN        NaN   9.475000
Massachusetts  cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.205400                NaN         NaN             NaN            NaN        NaN      NaN   9.160000  10.196667
Michigan       cluster 0     NaN             11.242            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.894800                NaN         NaN             NaN            NaN   9.216000   9.1530  10.477000  10.126556
Minnesota      cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.975000                NaN         NaN             NaN            NaN        NaN      NaN        NaN   9.454500
Mississippi    cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  13.493000
Missouri       cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.656000                NaN         NaN             NaN            NaN   9.565000      NaN   9.654000  11.630625
Montana        cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.269000                NaN         NaN             NaN       8.781000        NaN      NaN   8.731000   8.733000
Nebraska       cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                        9.422             NaN                  9.385   9.556846                NaN         NaN             NaN       9.299000        NaN   9.3665   9.345750   9.610625
Nevada         cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.681333                NaN         NaN             NaN            NaN        NaN      NaN   9.501500   9.813600
New Hampshire  cluster 0     NaN              9.523            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.693167                NaN         NaN           9.116       9.132000        NaN      NaN   9.186286   9.498900
New Jersey     cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.399000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  10.755250
New Mexico     cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  11.866000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  14.071500
New York       cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.994400                NaN         NaN             NaN       9.268000   9.131000      NaN  12.831000  10.199842
North Carolina cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  11.552000
North Dakota   cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   8.718800                NaN         NaN             NaN            NaN        NaN      NaN   8.613500   9.022400
Ohio           cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  12.018000                NaN         NaN             NaN            NaN        NaN  11.3290   9.275000  10.173929
Oklahoma       cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  13.726000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  11.967667
Oregon         cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  14.549000                NaN         NaN             NaN      14.112000        NaN      NaN        NaN   9.896000
Pennsylvania   cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.679941                NaN         NaN             NaN            NaN   9.408000  10.0800  10.044667  10.713417
Rhode Island   cluster 0  14.067                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.342600              9.265         NaN           9.241       9.268600   9.254000      NaN   9.274571   9.957143
South Carolina cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.936000                NaN         NaN             NaN            NaN   9.930000   9.9860   9.930000  12.729250
South Dakota   cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN           9.012                    NaN  10.754500                NaN       9.025             NaN       8.995333   9.129000   8.8960   9.138000   8.985000
Tennessee      cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  11.145000                NaN         NaN             NaN            NaN        NaN      NaN        NaN  11.472000
Texas          cluster 0  10.515                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.833000                NaN         NaN          10.390            NaN        NaN      NaN  10.583667  11.988947
Utah           cluster 0     NaN                NaN            NaN       9.388667                   NaN                  NaN                          NaN             NaN                    NaN   9.434471                NaN       9.476             NaN       9.443667   9.337333      NaN   9.349333   9.653333
Vermont        cluster 0     NaN                NaN            NaN       9.077000                   NaN               9.1975                          NaN             NaN                    NaN   9.056750                NaN       8.978           8.945            NaN   9.059000      NaN   9.010000   9.037625
Virginia       cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.179667                NaN         NaN             NaN            NaN        NaN      NaN   9.705000  12.496600
Washington     cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN  11.583500      NaN        NaN   9.722625
Washington DC  cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN   9.555500                NaN         NaN             NaN            NaN        NaN      NaN   9.568500        NaN
West Virginia  cluster 0     NaN                NaN            NaN            NaN                   NaN                  NaN                          NaN             NaN                    NaN        NaN                NaN         NaN             NaN            NaN        NaN      NaN        NaN  11.360000
Wisconsin      cluster 0     NaN                NaN         14.235            NaN                   NaN                  NaN                          NaN             NaN                    NaN  10.425000                NaN         NaN             NaN            NaN   8.941000      NaN   8.854000  11.014692
Wyoming        cluster 0     NaN                NaN            NaN            NaN                   NaN               9.1280                          NaN           9.313                    NaN   9.204286                NaN         NaN             NaN       8.961000        NaN   9.3090   9.179571  11.231143